import React, { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Brain, 
  Send, 
  Award, 
  Heart, 
  CheckCircle, 
  ArrowLeft, 
  RotateCcw, 
  AlertCircle, 
  Loader2, 
  TrendingDown
} from 'lucide-react';
import { reframeAPI } from '../../services/reframeApi';

// Pre-generated pixel-art sprites hosted on Cloudinary
const CHARACTER_SPRITES = {
  catastrophizing: "https://res.cloudinary.com/dxnpcuppm/image/upload/v1784916957/reframe_game/reframe_game/sprite_catastrophizing.jpg",
  black_and_white: "https://res.cloudinary.com/dxnpcuppm/image/upload/v1784917018/reframe_game/reframe_game/sprite_black_and_white.jpg",
  mind_reading: "https://res.cloudinary.com/dxnpcuppm/image/upload/v1784917018/reframe_game/reframe_game/sprite_mind_reading.jpg",
  overgeneralization: "https://res.cloudinary.com/dxnpcuppm/image/upload/v1784917019/reframe_game/reframe_game/sprite_overgeneralization.jpg"
};

// Indian Palace Themed private room backgrounds generated by Gemini (Nano Banana)
const ROOM_BACKGROUNDS = {
  catastrophizing: "https://res.cloudinary.com/dxnpcuppm/image/upload/v1784957894/reframe_game/reframe_game/room_indian_catastrophizing.jpg",
  black_and_white: "https://res.cloudinary.com/dxnpcuppm/image/upload/v1784957895/reframe_game/reframe_game/room_indian_black_white.jpg",
  mind_reading: "https://res.cloudinary.com/dxnpcuppm/image/upload/v1784957896/reframe_game/reframe_game/room_indian_mind_reading.jpg",
  overgeneralization: "https://res.cloudinary.com/dxnpcuppm/image/upload/v1784957897/reframe_game/reframe_game/room_indian_overgeneralization.jpg"
};

// Hardcoded opening statements per distortion type
const DEFAULT_OPENING_LINES = {
  catastrophizing: "One mistake here, and everything falls apart, you know that right?",
  black_and_white: "If you aren't completely perfect at this, you're a total failure.",
  mind_reading: "They are all looking at you and thinking how incompetent you are.",
  overgeneralization: "You always mess things up; this time won't be any different."
};

// Map configuration
const TILE_SIZE = 40;
const COLS = 20;
const ROWS = 15;

const preProcessDistortionName = (name) => {
  if (!name) return "";
  return name
    .split('_')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
};

// Client-side flood fill transparency processor
const floodFillAlpha = (imgData) => {
  const data = imgData.data;
  const width = imgData.width;
  const height = imgData.height;
  const visited = new Uint8Array(width * height);
  const queue = [];

  const getIndex = (x, y) => (y * width + x) * 4;

  const isWhite = (x, y) => {
    const idx = getIndex(x, y);
    return data[idx] > 220 && data[idx+1] > 220 && data[idx+2] > 220 && data[idx+3] > 0;
  };

  const add = (x, y) => {
    if (x >= 0 && x < width && y >= 0 && y < height) {
      const vIdx = y * width + x;
      if (!visited[vIdx] && isWhite(x, y)) {
        visited[vIdx] = 1;
        queue.push([x, y]);
      }
    }
  };

  // Seed from edges
  for (let x = 0; x < width; x++) {
    add(x, 0);
    add(x, height - 1);
  }
  for (let y = 0; y < height; y++) {
    add(0, y);
    add(width - 1, y);
  }

  while (queue.length > 0) {
    const [cx, cy] = queue.shift();
    const idx = getIndex(cx, cy);
    data[idx+3] = 0; // Transparent

    add(cx + 1, cy);
    add(cx - 1, cy);
    add(cx, cy + 1);
    add(cx, cy - 1);
  }
};

const makeImageTransparent = (imgUrl) => {
  return new Promise((resolve) => {
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.onload = () => {
      try {
        const canvas = document.createElement('canvas');
        canvas.width = img.width;
        canvas.height = img.height;
        const ctx = canvas.getContext('2d');
        ctx.drawImage(img, 0, 0);
        const imgData = ctx.getImageData(0, 0, canvas.width, canvas.height);
        
        floodFillAlpha(imgData);
        
        ctx.putImageData(imgData, 0, 0);
        resolve(canvas.toDataURL());
      } catch (e) {
        console.error("Transparency filter error:", e);
        resolve(imgUrl);
      }
    };
    img.onerror = () => resolve(imgUrl);
    img.src = imgUrl;
  });
};

const ReframeGame = ({ onExit }) => {
  const [stage, setStage] = useState('select'); // 'select', 'chat', 'settled'
  const [currentRoom, setCurrentRoom] = useState('rooftop'); // 'rooftop', 'lobby', 'distortion_room'
  const [distortionTypes, setDistortionTypes] = useState({});
  const [selectedType, setSelectedType] = useState('');
  const [intensity, setIntensity] = useState(100);
  const [chatLog, setChatLog] = useState([]);
  const [userInput, setUserInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);
  const [prefersReducedMotion, setPrefersReducedMotion] = useState(false);
  
  // Legend HUD box control
  const [showLegend, setShowLegend] = useState(true);

  // Retro Sprite States
  const [processedSprites, setProcessedSprites] = useState({});
  const spriteImagesRef = useRef({});

  // Depressed Player Sprite State
  const [processedPlayerSprite, setProcessedPlayerSprite] = useState(null);
  const playerImageRef = useRef(null);

  // Background Image States
  const bgImageRef = useRef(null);
  const [bgLoaded, setBgLoaded] = useState(false);

  const lobbyBgRef = useRef(null);
  const [lobbyBgLoaded, setLobbyBgLoaded] = useState(false);

  const outsideBgRef = useRef(null);
  const [outsideBgLoaded, setOutsideBgLoaded] = useState(false);

  const temple1BgRef = useRef(null);
  const [temple1BgLoaded, setTemple1BgLoaded] = useState(false);

  const temple2BgRef = useRef(null);
  const [temple2BgLoaded, setTemple2BgLoaded] = useState(false);

  const leftWingBgRef = useRef(null);
  const [leftWingBgLoaded, setLeftWingBgLoaded] = useState(false);

  // Themed private rooms image refs
  const roomBgImagesRef = useRef({});
  const [roomBgsLoaded, setRoomBgsLoaded] = useState(false);

  // Rain weather particles reference
  const rainParticles = useRef([]);

  // Web Audio Rain Loop Refs
  const rainSourceRef = useRef(null);
  const audioCtxRef = useRef(null);

  // Canvas viewport resize states
  const [canvasDimensions, setCanvasDimensions] = useState({
    width: window.innerWidth,
    height: window.innerHeight
  });

  // Canvas movement references
  const canvasRef = useRef(null);
  const player = useRef({
    x: 400, // Spawn centered on rooftop deck
    y: 350,
    radius: 12,
    speed: 150
  });

  const keysPressed = useRef({});
  const animationFrameId = useRef(null);
  const lastTime = useRef(0);
  const flashAlpha = useRef(0);
  const lastThunderTime = useRef(0);
  const chatEndRef = useRef(null);

  // Dynamic window resize handler for full screen selection
  useEffect(() => {
    if (stage !== 'select') return;
    const handleResize = () => {
      setCanvasDimensions({
        width: window.innerWidth,
        height: window.innerHeight
      });
    };
    window.addEventListener('resize', handleResize);
    handleResize();
    return () => window.removeEventListener('resize', handleResize);
  }, [stage]);

  // Synthesize realistic thunder cracks and rumbles procedurally using Web Audio API low-frequency noise
  const triggerThunderAudio = () => {
    try {
      const AudioContext = window.AudioContext || window.webkitAudioContext;
      const ctx = audioCtxRef.current || new AudioContext();
      
      const bufferSize = ctx.sampleRate * 2.5; // 2.5 seconds rumble
      const buffer = ctx.createBuffer(1, bufferSize, ctx.sampleRate);
      const data = buffer.getChannelData(0);
      for (let i = 0; i < bufferSize; i++) {
        data[i] = Math.random() * 2 - 1;
      }
      
      const noise = ctx.createBufferSource();
      noise.buffer = buffer;
      
      // Resonant Lowpass Filter to create the deep boom/rumble
      const filter = ctx.createBiquadFilter();
      filter.type = 'lowpass';
      filter.frequency.setValueAtTime(120, ctx.currentTime);
      filter.frequency.exponentialRampToValueAtTime(12, ctx.currentTime + 2.3);
      filter.Q.value = 4.0;
      
      const gain = ctx.createGain();
      gain.gain.setValueAtTime(0.0, ctx.currentTime);
      // Lightning strike crack peak
      gain.gain.linearRampToValueAtTime(0.35, ctx.currentTime + 0.05);
      gain.gain.exponentialRampToValueAtTime(0.01, ctx.currentTime + 2.4);
      
      noise.connect(filter);
      filter.connect(gain);
      gain.connect(ctx.destination);
      
      noise.start();
    } catch (e) {
      console.warn("Thunder sound generation failed:", e);
    }
  };

  // Audio rain looping control (Only playing when outside on the rooftop or courtyard)
  const startRainAudio = () => {
    if (currentRoom !== 'rooftop' && currentRoom !== 'outside') return; // Pause/mute indoors
    try {
      if (rainSourceRef.current) return; // Already running

      const AudioContext = window.AudioContext || window.webkitAudioContext;
      const audioContext = new AudioContext();
      audioCtxRef.current = audioContext;

      // Create white noise buffer
      const bufferSize = 2 * audioContext.sampleRate;
      const noiseBuffer = audioContext.createBuffer(1, bufferSize, audioContext.sampleRate);
      const output = noiseBuffer.getChannelData(0);
      for (let i = 0; i < bufferSize; i++) {
        output[i] = Math.random() * 2 - 1;
      }

      const whiteNoise = audioContext.createBufferSource();
      whiteNoise.buffer = noiseBuffer;
      whiteNoise.loop = true;

      // Filter to shape static white noise into gentle soft rain/wind sound
      const filter = audioContext.createBiquadFilter();
      filter.type = 'lowpass';
      filter.frequency.value = 850;

      const gain = audioContext.createGain();
      gain.gain.value = 0.08; // Translucent soft rain background loop

      whiteNoise.connect(filter);
      filter.connect(gain);
      gain.connect(audioContext.destination);

      whiteNoise.start();
      rainSourceRef.current = whiteNoise;
    } catch (e) {
      console.warn("Audio context failed to start:", e);
    }
  };

  const stopRainAudio = () => {
    if (rainSourceRef.current) {
      try {
        rainSourceRef.current.stop();
      } catch (e) {}
      rainSourceRef.current = null;
    }
    if (audioCtxRef.current) {
      try {
        audioCtxRef.current.close();
      } catch (e) {}
      audioCtxRef.current = null;
    }
  };

  // Manage rain audio loops dynamically during room transitions
  useEffect(() => {
    if (stage === 'select' && (currentRoom === 'rooftop' || currentRoom === 'outside')) {
      startRainAudio();
    } else {
      stopRainAudio();
    }
  }, [currentRoom, stage]);

  // Bind audio to user input interactions to support Chrome/Safari autoplay rules
  useEffect(() => {
    if (stage !== 'select' || (currentRoom !== 'rooftop' && currentRoom !== 'outside')) {
      stopRainAudio();
      return;
    }

    const triggerPlay = () => {
      startRainAudio();
    };

    window.addEventListener('click', triggerPlay);
    window.addEventListener('keydown', triggerPlay);

    return () => {
      window.removeEventListener('click', triggerPlay);
      window.removeEventListener('keydown', triggerPlay);
      stopRainAudio();
    };
  }, [stage, currentRoom]);

  // Auto-scroll chat to bottom
  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: prefersReducedMotion ? 'auto' : 'smooth' });
  }, [chatLog, prefersReducedMotion]);

  // Detect prefers-reduced-motion
  useEffect(() => {
    const mediaQuery = window.matchMedia('(prefers-reduced-motion: reduce)');
    setPrefersReducedMotion(mediaQuery.matches);
    const listener = (e) => setPrefersReducedMotion(e.matches);
    mediaQuery.addEventListener('change', listener);
    return () => mediaQuery.removeEventListener('change', listener);
  }, []);

  // Fetch distortion types on load
  useEffect(() => {
    const fetchTypes = async () => {
      try {
        setIsLoading(true);
        const data = await reframeAPI.getDistortionTypes();
        setDistortionTypes(data);
        setError(null);
      } catch (err) {
        console.error("Failed to load distortion types:", err);
        setError("Could not load distortion options. Please check your backend connection.");
      } finally {
        setIsLoading(false);
      }
    };
    fetchTypes();
  }, []);

  // Pre-process Cloudinary sprites on component mount
  useEffect(() => {
    const processAll = async () => {
      const processed = {};
      for (const [key, url] of Object.entries(CHARACTER_SPRITES)) {
        try {
          processed[key] = await makeImageTransparent(url);
        } catch (e) {
          processed[key] = url;
        }
      }
      setProcessedSprites(processed);

      // Pre-load Image objects for canvas drawing
      for (const [key, src] of Object.entries(processed)) {
        const img = new Image();
        img.src = src;
        spriteImagesRef.current[key] = img;
      }
    };
    processAll();
  }, []);

  // Pre-load background images from Cloudinary on mount
  useEffect(() => {
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.src = "https://res.cloudinary.com/dxnpcuppm/image/upload/v1784977371/reframe_game/reframe_game/background_indian_rooftop.jpg";
    img.onload = () => {
      bgImageRef.current = img;
      setBgLoaded(true);
    };

    // Load Indian palace hotel lobby background (only Mira, no other background people)
    const lobbyImg = new Image();
    lobbyImg.crossOrigin = "anonymous";
    lobbyImg.src = "https://res.cloudinary.com/dxnpcuppm/image/upload/v1784957893/reframe_game/reframe_game/background_indian_lobby.jpg";
    lobbyImg.onload = () => {
      lobbyBgRef.current = lobbyImg;
      setLobbyBgLoaded(true);
    };

    // Load Indian palace hotel outside background
    const outsideImg = new Image();
    outsideImg.crossOrigin = "anonymous";
    outsideImg.src = "https://res.cloudinary.com/dxnpcuppm/image/upload/v1784977373/reframe_game/reframe_game/background_indian_outside.jpg";
    outsideImg.onload = () => {
      outsideBgRef.current = outsideImg;
      setOutsideBgLoaded(true);
    };

    // Load Temple Floor 1 background
    const temple1Img = new Image();
    temple1Img.crossOrigin = "anonymous";
    temple1Img.src = "https://res.cloudinary.com/dxnpcuppm/image/upload/v1784979618/reframe_game/reframe_game/background_temple_floor_1.jpg";
    temple1Img.onload = () => {
      temple1BgRef.current = temple1Img;
      setTemple1BgLoaded(true);
    };

    // Load Temple Floor 2 background
    const temple2Img = new Image();
    temple2Img.crossOrigin = "anonymous";
    temple2Img.src = "https://res.cloudinary.com/dxnpcuppm/image/upload/v1784979619/reframe_game/reframe_game/background_temple_floor_2.jpg";
    temple2Img.onload = () => {
      temple2BgRef.current = temple2Img;
      setTemple2BgLoaded(true);
    };

    // Load Left Wing Palace building background
    const leftWingImg = new Image();
    leftWingImg.crossOrigin = "anonymous";
    leftWingImg.src = "https://res.cloudinary.com/dxnpcuppm/image/upload/v1784979620/reframe_game/reframe_game/background_left_wing_building.jpg";
    leftWingImg.onload = () => {
      leftWingBgRef.current = leftWingImg;
      setLeftWingBgLoaded(true);
    };

    // Load themed private rooms
    let loadedCount = 0;
    const total = Object.keys(ROOM_BACKGROUNDS).length;
    for (const [key, src] of Object.entries(ROOM_BACKGROUNDS)) {
      const roomImg = new Image();
      roomImg.crossOrigin = "anonymous";
      roomImg.src = src;
      roomImg.onload = () => {
        roomBgImagesRef.current[key] = roomImg;
        loadedCount++;
        if (loadedCount === total) {
          setRoomBgsLoaded(true);
        }
      };
    }
  }, []);

  // Pre-process player (depressed bearded man) sprite
  useEffect(() => {
    const playerUrl = "https://res.cloudinary.com/dxnpcuppm/image/upload/v1784919026/reframe_game/reframe_game/sprite_depressed_man.jpg";
    makeImageTransparent(playerUrl)
      .then((src) => {
        setProcessedPlayerSprite(src);
        const img = new Image();
        img.src = src;
        playerImageRef.current = img;
      })
      .catch(() => {
        setProcessedPlayerSprite(playerUrl);
        const img = new Image();
        img.src = playerUrl;
        playerImageRef.current = img;
      });
  }, []);

  // Initialize rain particles inside 800x600 coordinate bounds
  useEffect(() => {
    if (rainParticles.current.length === 0) {
      const particles = [];
      for (let i = 0; i < 60; i++) {
        particles.push({
          x: Math.random() * 800,
          y: Math.random() * 600,
          len: 10 + Math.random() * 15,
          speed: 300 + Math.random() * 200
        });
      }
      rainParticles.current = particles;
    }
  }, []);

  // Keyboard controls for canvas
  useEffect(() => {
    if (stage !== 'select') return;

    const handleKeyDown = (e) => {
      const key = e.key.toLowerCase();
      if (['arrowup', 'arrowdown', 'arrowleft', 'arrowright', 'w', 'a', 's', 'd'].includes(key)) {
        e.preventDefault();
      }
      keysPressed.current[key] = true;
    };

    const handleKeyUp = (e) => {
      const key = e.key.toLowerCase();
      keysPressed.current[key] = false;
    };

    window.addEventListener('keydown', handleKeyDown);
    window.addEventListener('keyup', handleKeyUp);

    return () => {
      window.removeEventListener('keydown', handleKeyDown);
      window.removeEventListener('keyup', handleKeyUp);
    };
  }, [stage]);

  // Canvas collision boundary checker (Enforces hallway boundaries, blocks walking off-map)
  const checkCollision = (newX, newY) => {
    const r = player.current.radius;
    
    if (currentRoom === 'rooftop') {
      // Keeps the player strictly on the rooftop brick deck floor, allowing stairs access on the left
      const minX = (newY >= 300 && newY <= 540) ? 60 : 120;
      if (newX - r < minX || newX + r > 680 || newY - r < 200 || newY + r > 540) {
        return true;
      }
    } else if (currentRoom === 'lobby') {
      // Allows walking anywhere inside the central hallway/reception area bounds
      if (newX - r < 200 || newX + r > 600 || newY - r < 60 || newY + r > 540) {
        return true;
      }
    } else if (currentRoom === 'distortion_room') {
      // Keeps the player inside the private distortion room walls
      if (newX - r < 60 || newX + r > 740 || newY - r < 60 || newY + r > 540) {
        return true;
      }
    } else if (currentRoom === 'outside') {
      // Keeps the player strictly in the outside courtyard area
      if (newX - r < 80 || newX + r > 720 || newY - r < 100 || newY + r > 550) {
        return true;
      }
    } else if (currentRoom === 'temple_floor_1' || currentRoom === 'temple_floor_2' || currentRoom === 'left_wing') {
      // General interior room bounds
      if (newX - r < 100 || newX + r > 700 || newY - r < 100 || newY + r > 540) {
        return true;
      }
    }
    return false;
  };

  // Check if player entered a lobby room doorway (Room 101/102/103/Lounge/Admin)
  const checkLobbyDoorEncounter = (x, y) => {
    if (currentRoom !== 'lobby') return null;
    
    // Left side door triggers (when hitting the left boundary)
    if (x <= 220) {
      if (y < 380) return 'catastrophizing';
      return 'black_and_white';
    }
    // Right side door triggers (when hitting the right boundary)
    if (x >= 580) {
      if (y < 380) return 'mind_reading';
      return 'overgeneralization';
    }
    
    return null;
  };

  // Top-down World Render Game Loop
  useEffect(() => {
    if (stage !== 'select' || !canvasRef.current) return;
    const canvas = canvasRef.current;
    const ctx = canvas.getContext('2d');
    lastTime.current = 0;

    const gameLoop = (timestamp) => {
      if (!lastTime.current) lastTime.current = timestamp;
      const dt = Math.min((timestamp - lastTime.current) / 1000, 0.1);
      lastTime.current = timestamp;

      // 1. Player movement
      let dx = 0;
      let dy = 0;

      if (keysPressed.current['w'] || keysPressed.current['arrowup']) dy -= 1;
      if (keysPressed.current['s'] || keysPressed.current['arrowdown']) dy += 1;
      if (keysPressed.current['a'] || keysPressed.current['arrowleft']) dx -= 1;
      if (keysPressed.current['d'] || keysPressed.current['arrowright']) dx += 1;

      if (dx !== 0 && dy !== 0) {
        const len = Math.sqrt(dx*dx + dy*dy);
        dx /= len;
        dy /= len;
      }

      const move = player.current.speed * dt;
      let nextX = player.current.x + dx * move;
      let nextY = player.current.y + dy * move;

      if (!checkCollision(nextX, player.current.y)) player.current.x = nextX;
      if (!checkCollision(player.current.x, nextY)) player.current.y = nextY;

      // Lock player Y on stairs diagonal incline
      if (currentRoom === 'rooftop' && player.current.x < 240) {
        player.current.y = 460 - (240 - player.current.x) * 0.6;
      }

      // Decay lightning flash
      if (flashAlpha.current > 0) {
        flashAlpha.current = Math.max(0, flashAlpha.current - dt * 2.0);
      }

      // Occasionally trigger procedural lightning strike (only when outdoors: rooftop or outside)
      if (currentRoom === 'rooftop' || currentRoom === 'outside') {
        if (Math.random() < 0.003 && (timestamp - lastThunderTime.current) > 5000) {
          flashAlpha.current = 0.85;
          lastThunderTime.current = timestamp;
          triggerThunderAudio();
        }
      }

      // 2. Door Transition checks (using robust coordinate-based sensor zones)
      if (currentRoom === 'rooftop') {
        // Stepped onto the rooftop Lobby door (centered exactly on doorway visual: X=215, Y=220)
        // Trigger transition if Y is near the top edge (< 235) and X is within the doorway [185, 245]
        if (player.current.y < 235 && player.current.x >= 185 && player.current.x <= 245) {
          setCurrentRoom('lobby');
          // Spawn player next to the lobby entry door safely (below the trigger zone)
          player.current.x = 420;
          player.current.y = 130;
          cancelAnimationFrame(animationFrameId.current);
          animationFrameId.current = requestAnimationFrame(gameLoop);
          return;
        }
      } else if (currentRoom === 'lobby') {
        // Check if player entered one of the lobby doors (leads to a private themed room)
        const enteredRoomType = checkLobbyDoorEncounter(player.current.x, player.current.y);
        if (enteredRoomType) {
          setSelectedType(enteredRoomType);
          setCurrentRoom('distortion_room');
          // Spawn player in the center of the private distortion room safely
          player.current.x = 400;
          player.current.y = 350;
          cancelAnimationFrame(animationFrameId.current);
          animationFrameId.current = requestAnimationFrame(gameLoop);
          return;
        }

        // Stepped onto the Lobby exit back to Rooftop door (centered at X=420, Y=60)
        // Trigger transition if Y is near the top edge (< 90) and X is within the door [380, 460]
        if (player.current.y < 90 && player.current.x >= 380 && player.current.x <= 460) {
          setCurrentRoom('rooftop');
          // Spawn safely on the rooftop deck outside the door trigger zone
          player.current.x = 215;
          player.current.y = 270;
          cancelAnimationFrame(animationFrameId.current);
          animationFrameId.current = requestAnimationFrame(gameLoop);
          return;
        }

        // Stepped onto the Lobby exit mat to leave building (centered at X=420, Y=560)
        // Trigger transition if Y is near the bottom edge (> 510) and X is within the door [380, 460]
        if (player.current.y > 510 && player.current.x >= 380 && player.current.x <= 460) {
          setCurrentRoom('outside');
          // Spawn player at the top center of the outside area, walking out of the hotel entrance door
          player.current.x = 400;
          player.current.y = 120;
          cancelAnimationFrame(animationFrameId.current);
          animationFrameId.current = requestAnimationFrame(gameLoop);
          return;
        }
      } else if (currentRoom === 'distortion_room') {
        // Stepped onto Lobby return door in private room (bottom-center ornate archway center X=490, Y=540)
        // Trigger transition if Y is near the bottom (> 510) and X is within the door [350, 630]
        if (player.current.y > 510 && player.current.x >= 350 && player.current.x <= 630) {
          setCurrentRoom('lobby');
          // Spawn player right in front of the door they just came out of (safely inside walkable bounds)
          if (selectedType === 'catastrophizing') { player.current.x = 240; player.current.y = 300; }
          else if (selectedType === 'black_and_white') { player.current.x = 240; player.current.y = 470; }
          else if (selectedType === 'mind_reading') { player.current.x = 560; player.current.y = 300; }
          else if (selectedType === 'overgeneralization') { player.current.x = 560; player.current.y = 470; }
          cancelAnimationFrame(animationFrameId.current);
          animationFrameId.current = requestAnimationFrame(gameLoop);
          return;
        }

        // Stepped onto the distortion NPC to trigger CBT reframe conversation
        const npcDist = Math.hypot(player.current.x - 400, player.current.y - 200);
        if (npcDist < 24) {
          cancelAnimationFrame(animationFrameId.current);
          keysPressed.current = {};
          handleStartGame(selectedType);
          return;
        }
      } else if (currentRoom === 'outside') {
        // Stepped onto Lobby entrance door in the outside courtyard (top center X: [360, 440], Y < 120)
        if (player.current.y < 120 && player.current.x >= 360 && player.current.x <= 440) {
          setCurrentRoom('lobby');
          // Spawn player next to the lobby entry door safely (above the exit mat trigger zone)
          player.current.x = 420;
          player.current.y = 480;
          cancelAnimationFrame(animationFrameId.current);
          animationFrameId.current = requestAnimationFrame(gameLoop);
          return;
        }

        // Stepped onto Left Wing entrance door in the outside courtyard (top left X: [80, 180], Y < 120)
        if (player.current.y < 120 && player.current.x >= 80 && player.current.x <= 180) {
          setCurrentRoom('left_wing');
          // Spawn player inside the left wing building hall
          player.current.x = 400;
          player.current.y = 480;
          cancelAnimationFrame(animationFrameId.current);
          animationFrameId.current = requestAnimationFrame(gameLoop);
          return;
        }

        // Stepped onto Temple entrance door in the outside courtyard (top right X: [580, 680], Y < 120)
        if (player.current.y < 120 && player.current.x >= 580 && player.current.x <= 680) {
          setCurrentRoom('temple_floor_1');
          // Spawn player inside Temple Floor 1
          player.current.x = 400;
          player.current.y = 480;
          cancelAnimationFrame(animationFrameId.current);
          animationFrameId.current = requestAnimationFrame(gameLoop);
          return;
        }

        // Exit the game if player walks off the bottom edge of the outside area
        if (player.current.y > 540) {
          cancelAnimationFrame(animationFrameId.current);
          stopRainAudio();
          handleBack();
          return;
        }
      } else if (currentRoom === 'left_wing') {
        // Stepped onto exit door in Left Wing hall (bottom center X: [350, 450], Y > 510)
        if (player.current.y > 510 && player.current.x >= 350 && player.current.x <= 450) {
          setCurrentRoom('outside');
          // Spawn player in front of Left Wing steps in the courtyard
          player.current.x = 130;
          player.current.y = 220;
          cancelAnimationFrame(animationFrameId.current);
          animationFrameId.current = requestAnimationFrame(gameLoop);
          return;
        }
      } else if (currentRoom === 'temple_floor_1') {
        // Stepped onto exit door in Temple Floor 1 (bottom center X: [350, 450], Y > 510)
        if (player.current.y > 510 && player.current.x >= 350 && player.current.x <= 450) {
          setCurrentRoom('outside');
          // Spawn player in front of Temple arches in the courtyard
          player.current.x = 630;
          player.current.y = 220;
          cancelAnimationFrame(animationFrameId.current);
          animationFrameId.current = requestAnimationFrame(gameLoop);
          return;
        }

        // Stepped onto stairs to Floor 2 (top left X: [100, 180], Y < 120)
        if (player.current.y < 120 && player.current.x >= 100 && player.current.x <= 180) {
          setCurrentRoom('temple_floor_2');
          // Spawn player at bottom-left stairs landing on Floor 2
          player.current.x = 140;
          player.current.y = 450;
          cancelAnimationFrame(animationFrameId.current);
          animationFrameId.current = requestAnimationFrame(gameLoop);
          return;
        }
      } else if (currentRoom === 'temple_floor_2') {
        // Stepped onto stairs to Floor 1 (bottom left X: [100, 180], Y > 510)
        if (player.current.y > 510 && player.current.x >= 100 && player.current.x <= 180) {
          setCurrentRoom('temple_floor_1');
          // Spawn player at top-left stairs landing on Floor 1
          player.current.x = 140;
          player.current.y = 140;
          cancelAnimationFrame(animationFrameId.current);
          animationFrameId.current = requestAnimationFrame(gameLoop);
          return;
        }
      }

      // 3. Save canvas context and apply scaling to stretch 800x600 map to cover full viewport edge-to-edge
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      ctx.save();
      
      const scaleX = canvas.width / 800;
      const scaleY = canvas.height / 600;
      ctx.scale(scaleX, scaleY);

      if (currentRoom === 'rooftop') {
        // Indian-style Rooftop rendering
        if (bgImageRef.current && bgLoaded) {
          ctx.drawImage(bgImageRef.current, 0, 0, 800, 600);
        } else {
          ctx.fillStyle = '#0f172a';
          ctx.fillRect(0, 0, 800, 600);
        }

        // Draw Dynamic Weather Rain (rooftop only)
        if (!prefersReducedMotion && rainParticles.current.length > 0) {
          ctx.strokeStyle = 'rgba(255, 255, 255, 0.14)';
          ctx.lineWidth = 1;
          rainParticles.current.forEach((p) => {
            ctx.beginPath();
            ctx.moveTo(p.x, p.y);
            ctx.lineTo(p.x - 2, p.y + p.len);
            ctx.stroke();

            p.y += p.speed * dt;
            p.x -= (p.speed * 0.18) * dt;

            if (p.y > 600) {
              p.y = -20;
              p.x = Math.random() * 800;
            }
          });
        }
      } else if (currentRoom === 'lobby') {
        // Ground Floor Lobby interior rendering
        if (lobbyBgRef.current && lobbyBgLoaded) {
          ctx.drawImage(lobbyBgRef.current, 0, 0, 800, 600);
        } else {
          ctx.fillStyle = '#451a03';
          ctx.fillRect(0, 0, 800, 600);
        }

        // Draw visual label for ROOFTOP exit (centered at top visually near door archway)
        ctx.fillStyle = '#ffffff';
        ctx.font = '8px "Press Start 2P"';
        ctx.textAlign = 'center';
        ctx.fillText("ROOFTOP", 420, 36);
      } else if (currentRoom === 'outside') {
        // Outside Courtyard rendering
        if (outsideBgRef.current && outsideBgLoaded) {
          ctx.drawImage(outsideBgRef.current, 0, 0, 800, 600);
        } else {
          ctx.fillStyle = '#0f172a';
          ctx.fillRect(0, 0, 800, 600);
        }

        // Draw visual labels for doorway interactions
        ctx.fillStyle = '#ffffff';
        ctx.font = '8px "Press Start 2P"';
        ctx.textAlign = 'center';
        ctx.fillText("PALACE WING", 130, 135);
        ctx.fillText("HOTEL LOBBY", 400, 135);
        ctx.fillText("TEMPLE", 630, 135);
        ctx.fillText("EXIT GAME", 400, 530);

        // Draw Dynamic Weather Rain (outside courtyard has rain too!)
        if (!prefersReducedMotion && rainParticles.current.length > 0) {
          ctx.strokeStyle = 'rgba(255, 255, 255, 0.14)';
          ctx.lineWidth = 1;
          rainParticles.current.forEach((p) => {
            ctx.beginPath();
            ctx.moveTo(p.x, p.y);
            ctx.lineTo(p.x - 2, p.y + p.len);
            ctx.stroke();

            p.y += p.speed * dt;
            p.x -= (p.speed * 0.18) * dt;

            if (p.y > 600) {
              p.y = -20;
              p.x = Math.random() * 800;
            }
          });
        }
      } else if (currentRoom === 'left_wing') {
        // Left Wing interior hall rendering
        if (leftWingBgRef.current && leftWingBgLoaded) {
          ctx.drawImage(leftWingBgRef.current, 0, 0, 800, 600);
        } else {
          ctx.fillStyle = '#1e1b4b';
          ctx.fillRect(0, 0, 800, 600);
        }

        ctx.fillStyle = '#ffffff';
        ctx.font = '8px "Press Start 2P"';
        ctx.textAlign = 'center';
        ctx.fillText("EXIT", 400, 530);
      } else if (currentRoom === 'temple_floor_1') {
        // Temple Floor 1 interior rendering
        if (temple1BgRef.current && temple1BgLoaded) {
          ctx.drawImage(temple1BgRef.current, 0, 0, 800, 600);
        } else {
          ctx.fillStyle = '#312e81';
          ctx.fillRect(0, 0, 800, 600);
        }

        ctx.fillStyle = '#ffffff';
        ctx.font = '8px "Press Start 2P"';
        ctx.textAlign = 'center';
        ctx.fillText("UP TO FLOOR 2", 140, 130);
        ctx.fillText("EXIT", 400, 530);
      } else if (currentRoom === 'temple_floor_2') {
        // Temple Floor 2 interior rendering
        if (temple2BgRef.current && temple2BgLoaded) {
          ctx.drawImage(temple2BgRef.current, 0, 0, 800, 600);
        } else {
          ctx.fillStyle = '#311042';
          ctx.fillRect(0, 0, 800, 600);
        }

        ctx.fillStyle = '#ffffff';
        ctx.font = '8px "Press Start 2P"';
        ctx.textAlign = 'center';
        ctx.fillText("DOWN TO FLOOR 1", 140, 530);
      } else if (currentRoom === 'distortion_room') {
        // Dedicated private themed room visualization from Nano Banana
        const themedRoomBg = roomBgImagesRef.current[selectedType];
        if (themedRoomBg && roomBgsLoaded) {
          // Draw high-detail custom room background from Cloudinary
          ctx.drawImage(themedRoomBg, 0, 0, 800, 600);
        } else {
          // Fallback cozy dark room if background is loading
          ctx.fillStyle = '#1e1b4b';
          ctx.fillRect(0, 0, 800, 120);
          ctx.fillStyle = '#2e2528';
          ctx.fillRect(0, 120, 800, 480);
          ctx.fillStyle = '#991b1b';
          ctx.fillRect(150, 200, 500, 260);
        }

        // Render Room text labels dynamically over doors (positioned over the bottom-center visual door arch)
        ctx.fillStyle = '#ffffff';
        ctx.font = '8px "Press Start 2P"';
        ctx.textAlign = 'center';
        ctx.fillText("LOBBY EXIT", 490, 545);

        ctx.fillStyle = '#2dd4bf';
        ctx.font = '12px "Press Start 2P"';
        ctx.fillText(preProcessDistortionName(selectedType).toUpperCase(), 400, 60);

        // Draw the single distortion NPC sprite centered in the room (Large size matching other characters)
        const npcImg = spriteImagesRef.current[selectedType];
        if (npcImg && npcImg.complete) {
          ctx.drawImage(
            npcImg,
            400 - 40,
            200 - 40,
            80,
            80
          );
        } else {
          ctx.fillStyle = '#a855f7';
          ctx.beginPath();
          ctx.arc(400, 200, 20, 0, Math.PI*2);
          ctx.fill();
        }

        // Window lightning animations (thunder flashes inside window frames)
        const THEMED_ROOM_WINDOWS = [
          { x: 60, y: 150, w: 280, h: 120 },
          { x: 60, y: 280, w: 280, h: 120 },
          { x: 60, y: 410, w: 280, h: 120 },
          { x: 390, y: 170, w: 250, h: 190 }
        ];

        THEMED_ROOM_WINDOWS.forEach((win) => {
          if (flashAlpha.current > 0) {
            ctx.save();
            ctx.beginPath();
            ctx.rect(win.x, win.y, win.w, win.h);
            ctx.clip();
            ctx.fillStyle = `rgba(224, 242, 254, ${flashAlpha.current * 0.9})`;
            ctx.fillRect(win.x, win.y, win.w, win.h);
            ctx.restore();
          }
        });
      }

      // Draw Grid Overlay lines (translucent for retro alignment)
      ctx.strokeStyle = 'rgba(71, 85, 105, 0.15)';
      ctx.lineWidth = 0.5;
      for (let r = 0; r < ROWS; r++) {
        for (let c = 0; c < COLS; c++) {
          ctx.strokeRect(c * TILE_SIZE, r * TILE_SIZE, TILE_SIZE, TILE_SIZE);
        }
      }

      // Draw player character sprite scaled up (with stair scaling on rooftop)
      let scaleFactor = 1.0;
      if (currentRoom === 'rooftop' && player.current.x < 240) {
        scaleFactor = 0.7 + ((player.current.x - 60) / 180) * 0.3;
        scaleFactor = Math.max(0.7, Math.min(1.0, scaleFactor));
      }
      const VISUAL_PLAYER_SIZE = 120 * scaleFactor;
      if (playerImageRef.current && playerImageRef.current.complete) {
        ctx.drawImage(
          playerImageRef.current,
          player.current.x - VISUAL_PLAYER_SIZE / 2,
          player.current.y - VISUAL_PLAYER_SIZE / 2,
          VISUAL_PLAYER_SIZE,
          VISUAL_PLAYER_SIZE
        );
      } else {
        ctx.fillStyle = '#14b8a6';
        ctx.fillRect(
          player.current.x - player.current.radius,
          player.current.y - player.current.radius,
          player.current.radius * 2,
          player.current.radius * 2
        );
      }

      // Draw dark radial ambient vignette
      const vignette = ctx.createRadialGradient(400, 300, 250, 400, 300, 520);
      vignette.addColorStop(0, 'rgba(0, 0, 0, 0)');
      vignette.addColorStop(1, 'rgba(0, 0, 0, 0.65)');
      ctx.fillStyle = vignette;
      ctx.fillRect(0, 0, 800, 600);

      // Draw full-screen lightning flash overlay when active (outdoors)
      if (flashAlpha.current > 0 && (currentRoom === 'rooftop' || currentRoom === 'outside')) {
        ctx.fillStyle = `rgba(224, 242, 254, ${flashAlpha.current * 0.6})`;
        ctx.fillRect(0, 0, 800, 600);
      }

      // Restore scaling context
      ctx.restore();

      animationFrameId.current = requestAnimationFrame(gameLoop);
    };

    animationFrameId.current = requestAnimationFrame(gameLoop);

    return () => {
      cancelAnimationFrame(animationFrameId.current);
    };
  }, [stage, bgLoaded, lobbyBgLoaded, outsideBgLoaded, temple1BgLoaded, temple2BgLoaded, leftWingBgLoaded, roomBgsLoaded, prefersReducedMotion, canvasDimensions, currentRoom, selectedType]);

  const handleStartGame = (typeKey) => {
    setSelectedType(typeKey);
    setIntensity(100);
    const openingText = DEFAULT_OPENING_LINES[typeKey] || "Things are looking pretty hopeless right now.";
    setChatLog([
      { sender: 'monster', text: openingText }
    ]);
    setStage('chat');
    setUserInput('');
    setError(null);
  };

  const handleSubmitReframe = async (e) => {
    e.preventDefault();
    if (!userInput.trim() || isLoading) return;

    const playerText = userInput.trim();
    setUserInput('');
    setError(null);

    setChatLog(prev => [...prev, { sender: 'player', text: playerText }]);
    setIsLoading(true);

    const lastMonsterMessage = [...chatLog]
      .reverse()
      .find(msg => msg.sender === 'monster');
    const monsterStatement = lastMonsterMessage ? lastMonsterMessage.text : "";

    try {
      const response = await reframeAPI.judgeReframe({
        distortion_type: selectedType,
        monster_statement: monsterStatement,
        player_reframe: playerText
      });

      const damageValue = response.damage || 0;
      const feedbackText = response.feedback;
      const nextMonsterResponse = response.monster_response;

      const newIntensity = Math.max(0, intensity - damageValue);
      setIntensity(newIntensity);

      setChatLog(prev => [
        ...prev,
        { 
          sender: 'feedback', 
          text: feedbackText, 
          isPositive: response.addresses_distortion 
        }
      ]);

      if (newIntensity <= 15) {
        setTimeout(() => {
          setStage('settled');
        }, prefersReducedMotion ? 0 : 800);
      } else {
        setChatLog(prev => [...prev, { sender: 'monster', text: nextMonsterResponse }]);
      }
    } catch (err) {
      console.error("Evaluation error:", err);
      setUserInput(playerText);
      setError("The connection to the judging engine failed. Please try sending your reframe again.");
    } finally {
      setIsLoading(false);
    }
  };

  const handleReset = () => {
    player.current.x = 400;
    player.current.y = 350;
    
    // Return player inside the dedicated private room instead of the lobby directly
    setCurrentRoom('distortion_room');
    setStage('select');
    setSelectedType(selectedType); // Retain room challenge selection
    setIntensity(100);
    setChatLog([]);
    setUserInput('');
    setError(null);
  };

  const handleBack = () => {
    if (onExit) {
      onExit();
    } else {
      window.location.href = '/';
    }
  };

  // Selection Phase (Full-Screen Scaled Interactive Map)
  if (stage === 'select') {
    return (
      <div className="w-screen h-screen bg-slate-950 text-white font-poppins relative overflow-hidden select-none">
        
        {/* HUD Absolute Nav Header */}
        <div className="absolute top-6 left-6 z-10 flex items-center gap-4">
          <button 
            onClick={handleBack}
            className="flex items-center gap-2 px-4 py-2 bg-slate-900/95 border-2 border-slate-700 hover:border-slate-500 rounded-none text-white font-pixel-body text-base transition backdrop-blur-sm shadow-md"
          >
            <ArrowLeft size={14} />
            BACK
          </button>
          <div className="flex items-center gap-2 bg-slate-900/95 px-4 py-2 border-2 border-slate-700 backdrop-blur-sm shadow-md">
            <Brain className="text-purple-400 w-5 h-5" />
            <span className="font-pixel-title text-xs text-teal-400 tracking-wider">
              {currentRoom === 'rooftop' ? "ROOFTOP DECK" : currentRoom === 'lobby' ? "BUILDING LOBBY" : "DISTORTION ROOM"}
            </span>
          </div>
        </div>

        {/* Full Viewport Canvas (Stretching the 800x600 map edge-to-edge) */}
        <canvas 
          ref={canvasRef} 
          width={canvasDimensions.width} 
          height={canvasDimensions.height}
          className="absolute inset-0 block bg-slate-950 cursor-default"
          style={{ imageRendering: 'pixelated' }}
        />

        {/* Closeable Legend & HUD Panel (Bottom-Left) */}
        {showLegend ? (
          <div className="absolute bottom-6 left-6 z-10 max-w-lg bg-slate-900/95 border-4 border-slate-700 rounded-none p-4 backdrop-blur-sm flex flex-col gap-3 shadow-lg animate-fade-in">
            
            {/* Legend Header with Close Action */}
            <div className="flex justify-between items-center border-b border-slate-800 pb-2">
              <h3 className="font-pixel-body text-base text-teal-400 font-bold flex items-center gap-2">
                <span>CONTROLS: WASD / ARROW KEYS</span>
              </h3>
              <button 
                onClick={() => setShowLegend(false)}
                className="text-slate-400 hover:text-white font-pixel-body font-bold text-sm px-2 bg-slate-950 border border-slate-700 hover:border-slate-500 rounded-none ml-4 transition"
                title="Close Info Panel"
              >
                X
              </button>
            </div>

            <p className="text-slate-300 text-xs leading-relaxed">
              {currentRoom === 'rooftop' 
                ? "You are outside on the observation deck. Walk directly into the arched brick building doorway to enter the Lobby."
                : currentRoom === 'lobby'
                ? "You are in the ground floor lobby. Walk into the doorways (Room 101, 102, 103, Lounge, Admin) to enter dedicated rooms. Stepping onto the bottom doorway EXITS the building."
                : "You are inside a private distortion room. Stepping onto the bottom-left door exits to the LOBBY. Stepping onto the top-left door transitions directly to the ROOFTOP."}
            </p>
          </div>
        ) : (
          /* Reopen panel floating help button */
          <button
            onClick={() => setShowLegend(true)}
            className="absolute bottom-6 left-6 z-10 px-4 py-2 bg-slate-900/95 border-2 border-slate-700 hover:border-slate-500 text-teal-400 font-pixel-body text-xs rounded-none backdrop-blur-sm transition shadow-md"
          >
            HELP / LEGEND
          </button>
        )}

      </div>
    );
  }

  // Conversation/Battle Phase Render
  return (
    <div className="min-h-screen bg-slate-950 text-white font-poppins flex flex-col p-6 overflow-x-hidden relative">
      
      {/* Dialogue Header */}
      <div className="flex items-center justify-between mb-6 max-w-7xl mx-auto w-full z-10">
        <button 
          onClick={handleReset}
          className="flex items-center gap-2 px-4 py-2 bg-slate-900 border-2 border-slate-700 hover:border-slate-500 rounded-none text-white font-pixel-body text-lg transition"
        >
          <ArrowLeft size={16} />
          SELECT DISTORTION
        </button>
        <div className="flex items-center gap-2">
          <span className="font-pixel-body text-xl text-teal-400 tracking-wider font-bold">
            {preProcessDistortionName(selectedType).toUpperCase()}
          </span>
        </div>
      </div>

      <div className="flex-1 max-w-7xl mx-auto w-full grid grid-cols-1 lg:grid-cols-12 gap-8 items-stretch z-10 mb-6">
        
        {/* Left Column: Portrait, Stats & Clarity meter */}
        <div className="lg:col-span-4 flex flex-col gap-6">
          <div className="bg-slate-900 border-4 border-slate-700 rounded-none p-6 flex flex-col gap-6 shadow-none h-full justify-between">
            <div>
              <span className="font-pixel-body text-sm uppercase font-bold tracking-wider text-purple-400">Current Pattern</span>
              <h2 className="font-pixel-body text-3xl font-bold mt-1 text-white leading-tight">
                {preProcessDistortionName(selectedType)}
              </h2>
              
              {/* Character Portrait */}
              <div className="w-full aspect-square bg-slate-950 border-4 border-slate-700 rounded-none overflow-hidden my-4">
                <img 
                  src={processedSprites[selectedType] || CHARACTER_SPRITES[selectedType]} 
                  alt={selectedType}
                  className="w-full h-full object-cover"
                  style={{ imageRendering: 'pixelated' }}
                />
              </div>

              <p className="text-slate-300 text-sm leading-relaxed border-b border-slate-700 pb-4">
                {distortionTypes[selectedType]}
              </p>

              {/* Clarity meter */}
              <div className="mt-6 space-y-3">
                <div className="flex justify-between items-end">
                  <span className="font-pixel-body text-base text-slate-400 font-semibold flex items-center gap-1">
                    <TrendingDown size={16} className="text-teal-400" />
                    DISTORTION INTENSITY
                  </span>
                  <span className={`font-pixel-body text-lg font-bold ${intensity > 50 ? 'text-red-400' : 'text-teal-400'}`}>
                    {intensity}%
                  </span>
                </div>
                <div className="bg-slate-950 border-4 border-slate-700 rounded-none h-7 relative p-[2px]">
                  <div 
                    className="h-full bg-red-700 transition-all duration-700 ease-out"
                    style={{ width: `${intensity}%` }}
                  />
                </div>
                <p className="text-xs text-slate-400 leading-relaxed italic mt-2">
                  Dismantle the negative voice by providing realistic, balanced perspectives. Reduce distortion intensity below 15% to resolve the thought.
                </p>
              </div>
            </div>

            {/* Support box */}
            <div className="bg-slate-950 border-2 border-teal-800 rounded-none p-4">
              <h4 className="font-pixel-body text-sm text-teal-400 font-bold mb-1 flex items-center gap-1">
                <Heart size={14} />
                CBT GUIDANCE
              </h4>
              <p className="text-xs text-slate-300 leading-relaxed">
                Take a deep breath. Focus on gathering evidence against the negative claim. Try to think what you would say to a close friend facing the same doubt.
              </p>
            </div>
          </div>
        </div>

        {/* Right Column: Chat Screen */}
        <div className="lg:col-span-8 flex flex-col bg-slate-900 border-4 border-slate-700 rounded-none p-6 shadow-none h-[600px] lg:h-auto justify-between">
          
          {/* Chat message feed */}
          <div className="flex-1 overflow-y-auto space-y-4 p-4 mb-4 bg-slate-950 border-4 border-slate-800 rounded-none flex flex-col justify-start">
            <AnimatePresence initial={false}>
              {chatLog.map((msg, index) => {
                if (msg.sender === 'monster') {
                  return (
                    <motion.div 
                      key={index}
                      className="flex flex-col max-w-[85%] self-start"
                      initial={prefersReducedMotion ? {} : { opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ duration: 0.4 }}
                    >
                      <span className="font-pixel-body text-xs text-purple-400 uppercase tracking-widest font-bold ml-1 mb-1">
                        Negative Voice
                      </span>
                      <div className="bg-purple-950 border-2 border-purple-800 text-purple-100 rounded-none p-4 shadow-none leading-relaxed text-sm">
                        {msg.text}
                      </div>
                    </motion.div>
                  );
                } else if (msg.sender === 'player') {
                  return (
                    <motion.div 
                      key={index}
                      className="flex flex-col max-w-[85%] self-end"
                      initial={prefersReducedMotion ? {} : { opacity: 0, x: 20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ duration: 0.4 }}
                    >
                      <span className="font-pixel-body text-xs text-teal-400 uppercase tracking-widest font-bold mr-1 mb-1 text-right">
                        Your Reframe
                      </span>
                      <div className="bg-indigo-950 border-2 border-indigo-700 text-white rounded-none p-4 shadow-none leading-relaxed text-sm">
                        {msg.text}
                      </div>
                    </motion.div>
                  );
                } else {
                  // Feedback from evaluation
                  return (
                    <motion.div 
                      key={index}
                      className="w-full flex justify-center py-2"
                      initial={prefersReducedMotion ? {} : { opacity: 0, scale: 0.95 }}
                      animate={{ opacity: 1, scale: 1 }}
                      transition={{ duration: 0.4 }}
                    >
                      <div className={`flex items-start gap-3 rounded-none p-4 border max-w-[90%] text-sm leading-relaxed ${
                        msg.isPositive 
                          ? 'bg-teal-950/40 border-teal-800/40 text-teal-200' 
                          : 'bg-amber-950/40 border-amber-800/40 text-amber-200'
                      }`}>
                        <div className="mt-[2px] flex-shrink-0">
                          {msg.isPositive ? <CheckCircle size={18} className="text-teal-400" /> : <AlertCircle size={18} className="text-amber-400" />}
                        </div>
                        <div>
                          <span className="font-pixel-body text-xs block uppercase font-bold tracking-wider text-slate-400 mb-1">
                            CBT REFLECTION
                          </span>
                          {msg.text}
                        </div>
                      </div>
                    </motion.div>
                  );
                }
              })}
            </AnimatePresence>

            {isLoading && (
              <motion.div 
                className="flex items-center gap-2 self-start bg-slate-900 border-2 border-slate-800 rounded-none p-4 text-slate-400 text-sm font-pixel-body"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
              >
                <Loader2 className="w-4 h-4 animate-spin text-teal-400" />
                EVALUATING THOUGHT REFRAME...
              </motion.div>
            )}

            <div ref={chatEndRef} />
          </div>

          {/* Form input panel */}
          <form onSubmit={handleSubmitReframe} className="space-y-3">
            {error && (
              <div className="flex items-center gap-2 bg-red-950/40 border-2 border-red-800 rounded-none p-3 text-red-200 text-sm">
                <AlertCircle size={16} className="text-red-400 flex-shrink-0" />
                <p className="flex-1 font-pixel-body">{error}</p>
              </div>
            )}

            <div className="relative flex flex-col md:flex-row items-stretch gap-3">
              <textarea
                value={userInput}
                onChange={(e) => setUserInput(e.target.value)}
                placeholder="Type your healthy reframe here..."
                disabled={isLoading || stage === 'settled'}
                maxLength={400}
                className="flex-1 bg-slate-950 border-2 border-slate-700 rounded-none p-4 text-white placeholder-slate-500 focus:outline-none focus:border-purple-500 resize-none min-h-[80px] disabled:opacity-50 text-sm leading-relaxed"
                onKeyDown={(e) => {
                  if (e.key === 'Enter' && !e.shiftKey) {
                    e.preventDefault();
                    handleSubmitReframe(e);
                  }
                }}
              />
              <button
                type="submit"
                disabled={!userInput.trim() || isLoading || stage === 'settled'}
                className="px-6 py-3 bg-slate-800 hover:bg-slate-700 border-4 border-slate-600 disabled:border-slate-800 disabled:bg-slate-900 text-white font-pixel-body text-base font-bold rounded-none shadow-none transition duration-200 flex items-center justify-center gap-2 self-end md:self-stretch disabled:opacity-50"
              >
                <Send size={18} />
                SEND
              </button>
            </div>

            <div className="flex justify-between items-center text-xs text-slate-400 px-1 font-pixel-body">
              <span>Press Enter to send</span>
              <span>{userInput.length}/400 chars</span>
            </div>
          </form>
        </div>
      </div>

      {/* Settle Resolution Overlay Stage */}
      <AnimatePresence>
        {stage === 'settled' && (
          <motion.div 
            className="fixed inset-0 z-50 bg-slate-950/90 backdrop-blur-sm flex items-center justify-center p-6"
            initial={prefersReducedMotion ? {} : { opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
          >
            <motion.div 
              className="bg-slate-900 border-8 border-slate-700 rounded-none p-8 max-w-xl w-full text-center shadow-none relative overflow-hidden"
              initial={prefersReducedMotion ? {} : { scale: 0.9, y: 50 }}
              animate={{ scale: 1, y: 0 }}
              exit={{ scale: 0.9, y: 50 }}
              transition={{ duration: 0.5, type: 'spring' }}
            >
              <div className="w-20 h-20 bg-slate-950 border-4 border-teal-500 rounded-none flex items-center justify-center mx-auto mb-6 text-teal-400">
                <CheckCircle size={40} className="animate-pulse" />
              </div>

              <h2 className="text-xl md:text-2xl font-pixel-title leading-relaxed mb-6 text-teal-400">
                THE THOUGHT HAS SETTLED
              </h2>

              <p className="text-slate-300 text-base leading-relaxed mb-8">
                Through mindful CBT reframing, you have successfully dismantled the negative distortion and reduced its intensity down to <span className="text-teal-400 font-bold">{intensity}%</span>. The voice has lost its grip, and calm clarity is restored to your mind.
              </p>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <button
                  onClick={handleReset}
                  className="px-6 py-4 bg-slate-950 border-4 border-slate-700 hover:border-slate-500 rounded-none text-white font-pixel-body text-lg font-bold transition flex items-center justify-center gap-2"
                >
                  <RotateCcw size={18} />
                  REFRAME ANOTHER
                </button>
                <button
                  onClick={handleBack}
                  className="px-6 py-4 bg-gradient-to-r from-teal-500 to-emerald-600 border-4 border-teal-400 text-slate-950 font-pixel-body text-lg font-bold rounded-none shadow-none transition flex items-center justify-center gap-2 hover:scale-[1.02]"
                >
                  <Award size={18} />
                  COMPLETE SESSION
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};

export default ReframeGame;
